# Generated by Django 5.2.8 on 2025-11-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='$', max_length=5),
        ),
    ]
