# Generated by Django 5.2.8 on 2025-11-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_product_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_favorite',
        ),
    ]
